# pull official base image
FROM node:16-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY . ./
# install app dependencies
COPY package.json ./
COPY package-lock.json ./


RUN npm install

# error node modules .cache
RUN chown node:node /app/node_modules
RUN chmod -R 777 /app/node_modules/.cache

# add app

USER node

# start app
CMD ["npm", "start"]

